
USE sys;

CREATE TABLE PRODUCT (
    PRO_NO CHAR(10) PRIMARY KEY,
    PRO_NAME VARCHAR(30),
    PRO_M_NO TINYINT UNSIGNED DEFAULT 1,
    PRO_PRICE INT UNSIGNED DEFAULT 0
);

CREATE TABLE MAKER (
    M_NO TINYINT UNSIGNED DEFAULT 1,
    M_NAME VARCHAR(30)
);

SELECT * FROM PRODUCT;
SELECT * FROM MAKER;