-- 관리자 계정으로 진행 - root
-- db 생성
CREATE DATABASE SCOTT DEFAULT CHARACTER SET UTF8MB4 COLLATE UTF8MB4_GENERAL_CI;
SHOW DATABASES;
DROP DATABASE SCOTT;
# DB 문자코드 변경
ALTER DATABASE 디비명 DEFAULT CHARACTER SET UTF8MB4 COLLATE UTF8MB4_GENERAL_CI;

# 계정 생성
CREATE USER 'SCOTT'@'%' IDENTIFIED BY '123456';
# 모든 권한 부여
GRANT ALL PRIVILEGES ON SCOTT.* TO 'SCOTT'@'%';
#권한 회수 방법
REVOKE ALL PRIVILEGES ON SCOTT.* FROM 'SCOTT'@'%';

# DB 선택
USE SCOTT;

# 학생 테이블
CREATE TABLE STUDENT(
	STD_NO CHAR(8) PRIMARY KEY,
	STD_NAME VARCHAR(30),
	MAJOR_NO DECIMAL(2) DEFAULT 0,
	STD_SCORE FLOAT(3,2)
);

INSERT INTO STUDENT VALUES('20220755', '김철수', 1, 3.8);
INSERT INTO STUDENT VALUES('20220756', '이영희', 2, 3.5);
INSERT INTO STUDENT VALUES('20220757', '박민수', 1, 2.9);
INSERT INTO STUDENT VALUES('20220758', '최지우', 3, 4.0);
INSERT INTO STUDENT VALUES('20220759', '정수현', 2, 3.1);

SELECT * FROM STUDENT;

